#debug: true
server: 
  port: 8080 
  servlet: 
    context-path: /SpringBootJpaTows
  #修改tomcat的URIEncoding为UTF-8
  tomcat: 
    uri-encoding: UTF-8

spring: 
#  profiles: 
#    active: dev # dev是配置文件application-{}.yml的中间名
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/springjpacrm?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root 
    password: root 
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000                          # 等待连接获取的最大超时时间
  # SpringDateJpa 配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  jpa: 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
    ##运行时输出jpa执行的sql语句
    show-sql: true
    ## spring-boot-starter-data-jpa自动映射创建表动作 配置: 有表更新,无表创建
    hibernate: 
      ddl-auto: update
  #     spring mvc 视图解析器   
  mvc: 
    view: 
      prefix: /
      suffix: .html
  #集中解决各种编码问题
  banner: 
   charset: UTF-8
  http: 
    encoding: 
      charset: UTF-8
      enabled: true 
      force: true
  messages:
    encoding: UTF-8
  # 时间格式化 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss 
  # 时区设置
    time-zone: GMT+8 
     
  
